import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <nav className={styles.nav}>
          <Link href="/" className={styles.brand}>
            Mateusz Lisowski
          </Link>

          <input
            type="checkbox"
            id="menu-toggle"
            className={styles.menuToggle}
          />
          <label htmlFor="menu-toggle" className={styles.hamburger}>
            ☰
          </label>

          <div>
            <label htmlFor="menu-toggle" className={styles.closeBtn}>
              ✕
            </label>
            <a href="/about" className={styles.link}>
              O mnie
            </a>
            <a href="/offer" className={styles.link}>
              Oferta
            </a>
            <a href="/blog" className={styles.link}>
              Blog
            </a>
            <a href="/contact" className={styles.link}>
              Kontakt
            </a>
          </div>
        </nav>
        <div>SOCIAL MEDIA TODO ikonki xd</div>
        <footer className="w-full mt-15 h-12 flex items-center justify-center border-t">
          Copyright © 2026 Mateusz Lisowski. Wszelkie prawa zastrzeżone.
        </footer>
      </body>
    </html>
  );
}
